apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server-deployment
  labels:
    app: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
      annotations:
        # WARNING: This simulates the service account being exposed via an annotation.
        cloud.google.com/service_account: "name@prod-project-id.iam.gserviceaccount.com"
    spec:
      containers:
      - name: echo-server
        image: docker.io/joelmorales402/bh-aisec-project_1-echo-server@sha256:eaaee89dd74f070bbae235680cc6ee0ce2f6475d947d4f138900620916e7dfe9
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server-service
spec:
  selector:
    app: echo-server
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort # Exposes the service on a port on each node's IP
